version: "3.9"

networks:
  webapp:
services:
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    networks:
      - webapp
  backend:
    build: ./backend
    ports:
      - 5000:4000
    networks:
      - webapp
    depends_on:
      - mongodb
  mongodb:
    container_name: web-mongodb
    image: mongo:4.0-rc-xenial
    networks:
      - webapp
